[debug] [2020-04-25T00:24:52.882Z] ----------------------------------------------------------------------
[debug] [2020-04-25T00:24:52.885Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\CamiloPati単oVelez\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2020-04-25T00:24:52.885Z] CLI Version:   8.1.1
[debug] [2020-04-25T00:24:52.885Z] Platform:      win32
[debug] [2020-04-25T00:24:52.885Z] Node Version:  v12.16.2
[debug] [2020-04-25T00:24:52.895Z] Time:          Fri Apr 24 2020 19:24:52 GMT-0500 (GMT-05:00)
[debug] [2020-04-25T00:24:52.895Z] ----------------------------------------------------------------------
[debug] [2020-04-25T00:24:52.895Z] 
[debug] [2020-04-25T00:24:52.910Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-25T00:24:52.947Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\CamiloPati単oVelez\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\CamiloPati単oVelez\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\CamiloPati単oVelez\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
